name: frontend
description: A new Flutter project.

version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^1.2.0
  get: ^4.6.5
  flutter_dotenv: ^5.0.2
  file_picker: ^6.1.1
  image_picker: ^0.8.4+2
  flutter:
    sdk: flutter
  camera: ^0.10.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.5.2
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  socket_io_client: ^2.0.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
